/**
 * Browser Test Infrastructure
 * ===========================
 *
 * Browser tests use Playwright (headless Chromium) to verify CSS layout behavior
 * against **real HTML generated by the Rust pipeline** — never hardcoded replicas.
 *
 * ## How it works
 *
 * 1. **globalSetup** (`setup.ts`) runs once before the suite:
 *    `cargo run -- build --source fixtures/browser-content --output tests/browser/generated`
 *    This executes the full scan → process → generate pipeline on dedicated fixture
 *    content, producing real HTML with real inline CSS.
 *
 * 2. **Fixture content** lives in `fixtures/browser-content/`:
 *    - `010-No-Description/` — landscape image, no sidecar .txt
 *    - `020-With-Caption/`   — landscape + portrait images with short captions (≤160 chars)
 *    - `030-With-Description/` — landscape + portrait images with long descriptions (>160 chars)
 *    Images are small synthetic JPEGs (600×400 landscape, 400×600 portrait).
 *
 * 3. **Tests** load generated pages via `loadGeneratedPage()` and assert on
 *    computed bounding boxes, scroll metrics, and element positions.
 *
 * ## CSS variable overrides
 *
 * Some tests need to vary parameters (e.g., aspect ratio) without a separate fixture
 * image for each value. `loadGeneratedPage` accepts a `cssOverrides` map that injects
 * `:root { --var: value !important }` before `</style>`. The HTML structure and all
 * other CSS rules remain real.
 *
 * ## Adding new test scenarios
 *
 * - **New page variant**: add fixture content to `fixtures/browser-content/`, add
 *   the generated path to the `pages` registry below.
 * - **New layout test**: import `loadGeneratedPage` and `pages`, pick a page, assert.
 * - **Parameterized test**: use `cssOverrides` to vary CSS custom properties.
 *
 * ## Why this matters
 *
 * CSS and HTML structure come from the real code path. If `static/style.css` or
 * `generate.rs` changes, globalSetup recompiles and regenerates — tests catch
 * regressions automatically. No hand-maintained CSS replica to keep in sync.
 */

import { Page } from "@playwright/test";
import fs from "fs";
import path from "path";

const GENERATED_DIR = path.join(__dirname, "generated");

/**
 * Load a generated HTML page into the Playwright page.
 *
 * Reads the real HTML produced by the Rust pipeline and sets it as page content.
 * Optionally overrides CSS custom properties (e.g., to test different aspect ratios
 * without needing a separate fixture image for each).
 *
 * @param page - Playwright page instance
 * @param relativePath - Path relative to the generated output dir (e.g., "With-Caption/1-landscape/index.html")
 * @param cssOverrides - Optional CSS custom property overrides (e.g., { "--aspect-ratio": "0.5" })
 */
export async function loadGeneratedPage(
  page: Page,
  relativePath: string,
  cssOverrides?: Record<string, string>,
): Promise<void> {
  const filePath = path.join(GENERATED_DIR, relativePath);
  let html = fs.readFileSync(filePath, "utf-8");

  if (cssOverrides) {
    const vars = Object.entries(cssOverrides)
      .map(([k, v]) => `${k}: ${v} !important;`)
      .join(" ");
    html = html.replace("</style>", `:root { ${vars} }\n</style>`);
  }

  await page.setContent(html);
}

/** Generated image page paths for browser test fixtures. */
export const pages = {
  noDescription: {
    landscape: "No-Description/1-landscape/index.html",
  },
  withCaption: {
    landscape: "With-Caption/1-landscape/index.html",
    portrait: "With-Caption/2-portrait/index.html",
  },
  withDescription: {
    landscape: "With-Description/1-landscape/index.html",
    portrait: "With-Description/2-portrait/index.html",
  },
  albums: {
    noDescription: "No-Description/index.html",
    withCaption: "With-Caption/index.html",
    withDescription: "With-Description/index.html",
  },
  index: "index.html",
};
