name: 'Rust Setup'
description: 'Install Rust toolchain and cache everything'

inputs:
  rust-components:
    description: 'Extra rustup components (e.g. clippy, rustfmt)'
    required: false
    default: ''
  targets:
    description: 'Extra Rust targets to install'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.rust-components }}
        targets: ${{ inputs.targets }}

    - name: Cache Cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-${{ inputs.targets || 'native' }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.targets || 'native' }}-cargo-
